"""
brain/commands/init.py
First-time setup wizard — detects vault, configures provider, writes .env
"""

import os
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.table import Table
from rich import box

console = Console()

# Common Obsidian vault locations to auto-detect
COMMON_VAULT_PATHS = [
    "~/Documents/Obsidian",
    "~/Obsidian",
    "~/Desktop/Obsidian",
    "~/Notes",
    "~/Documents/Notes",
    "~/vaults",
    "~/Desktop/Notes",
]


def _find_vaults() -> list[Path]:
    """Scan common paths for Obsidian vaults (.obsidian folder marker)."""
    found = []
    for pattern in COMMON_VAULT_PATHS:
        base = Path(pattern).expanduser()
        if not base.exists():
            continue
        # Check if base itself is a vault
        if (base / ".obsidian").exists():
            found.append(base)
            continue
        # Check one level deep
        try:
            for child in base.iterdir():
                if child.is_dir() and (child / ".obsidian").exists():
                    found.append(child)
        except PermissionError:
            continue
    return found


def _pick_vault(found: list[Path]) -> Path:
    """Let user pick from detected vaults or enter a custom path."""
    if found:
        console.print("\n[bold]Detected Obsidian vaults:[/]")
        table = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
        table.add_column("Index", style="cyan")
        table.add_column("Path", style="white")

        for i, v in enumerate(found, 1):
            table.add_row(str(i), str(v))
        table.add_row("0", "Enter a custom path")
        console.print(table)

        choice = Prompt.ask(
            "Select vault",
            choices=[str(i) for i in range(len(found) + 1)],
            default="1",
        )
        if choice != "0":
            return found[int(choice) - 1]

    # Manual path entry
    while True:
        raw = Prompt.ask("\nEnter your vault path")
        path = Path(raw).expanduser().resolve()
        if path.exists():
            if not (path / ".obsidian").exists():
                if Confirm.ask(f"  [yellow]No .obsidian folder found at {path}. Use anyway?[/]"):
                    return path
            else:
                return path
        else:
            console.print(f"  [red]Path does not exist:[/] {path}")


def _pick_provider() -> str:
    """Let user pick LLM provider."""
    console.print("\n[bold]Choose LLM provider:[/]")
    table = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    table.add_column("Key", style="cyan")
    table.add_column("Provider")
    table.add_column("Notes", style="dim")
    table.add_row("1", "Ollama", "fully local, no API key needed")
    table.add_row("2", "Groq", "fastest, free tier, needs API key")
    table.add_row("3", "Gemini", "free tier, needs API key, also handles embeddings")
    console.print(table)

    choice = Prompt.ask("Select provider", choices=["1", "2", "3"], default="1")
    return {"1": "ollama", "2": "groq", "3": "gemini"}[choice]


def _get_api_key(provider: str) -> str:
    """Prompt for API key with masked input."""
    urls = {
        "groq": "https://console.groq.com/keys",
        "gemini": "https://aistudio.google.com/app/apikey",
    }
    console.print(f"\n  Get your key at: [cyan]{urls.get(provider, '')}[/]")
    import getpass
    key = getpass.getpass(f"  Enter {provider.upper()}_API_KEY (hidden): ").strip()
    return key


def _write_env(vault_path: Path, provider: str, groq_key: str, gemini_key: str, env_path: Path):
    """Write .env file."""
    lines = [
        "# Obsidian Brain configuration",
        "# Generated by: brain init",
        "",
        f"BRAIN_VAULT_PATH={vault_path}",
        f"BRAIN_LLM_PROVIDER={provider}",
        "",
        "# API Keys",
        f"GROQ_API_KEY={groq_key}",
        f"GEMINI_API_KEY={gemini_key}",
    ]
    env_path.write_text("\n".join(lines) + "\n")


def _verify_setup(vault_path: Path, provider: str):
    """Run a quick verification after setup."""
    console.print("\n[dim]Verifying setup...[/]\n")

    # Check vault
    md_files = list(vault_path.rglob("*.md"))
    if md_files:
        console.print(f"  [green]✓[/] Vault found — {len(md_files)} markdown files detected")
    else:
        console.print(f"  [yellow]![/] Vault path set but no .md files found")

    # Check Ollama if needed
    if provider == "ollama":
        try:
            import ollama
            ollama.list()
            console.print("  [green]✓[/] Ollama is running")
        except Exception:
            console.print("  [yellow]![/] Ollama is not running — start it with: [cyan]ollama serve[/]")

    # Check API keys
    from dotenv import load_dotenv
    load_dotenv()
    if provider == "groq":
        key = os.getenv("GROQ_API_KEY", "")
        if key:
            console.print("  [green]✓[/] GROQ_API_KEY is set")
        else:
            console.print("  [red]✗[/] GROQ_API_KEY missing")
    elif provider == "gemini":
        key = os.getenv("GEMINI_API_KEY", "")
        if key:
            console.print("  [green]✓[/] GEMINI_API_KEY is set")
        else:
            console.print("  [red]✗[/] GEMINI_API_KEY missing")


def run_init():
    """Main init wizard."""
    console.print(Panel(
        "[bold]Obsidian Brain — Setup Wizard[/]\n"
        "[dim]This will configure your vault path, LLM provider, and API keys.\n"
        "Takes about 2 minutes.[/]",
        border_style="cyan",
    ))

    # --- Step 1: Vault ---
    console.print("\n[bold cyan]Step 1 of 3[/] — Find your Obsidian vault")
    with console.status("[dim]Scanning for vaults...[/]"):
        found = _find_vaults()

    if found:
        console.print(f"  Found [cyan]{len(found)}[/] vault(s)")
    else:
        console.print("  [dim]No vaults auto-detected — you'll enter the path manually.[/]")

    vault_path = _pick_vault(found)
    console.print(f"\n  [green]✓[/] Vault set to: [cyan]{vault_path}[/]")

    # --- Step 2: Provider ---
    console.print("\n[bold cyan]Step 2 of 3[/] — Choose LLM provider")
    provider = _pick_provider()
    console.print(f"\n  [green]✓[/] Provider set to: [cyan]{provider}[/]")

    # --- Step 3: API Keys ---
    groq_key = ""
    gemini_key = ""

    console.print("\n[bold cyan]Step 3 of 3[/] — API keys")

    if provider == "ollama":
        console.print("  [dim]Ollama needs no API key.[/]")
        if Confirm.ask("  Add Groq/Gemini keys as fallback providers?", default=False):
            if Confirm.ask("  Add Groq API key?", default=False):
                groq_key = _get_api_key("groq")
            if Confirm.ask("  Add Gemini API key?", default=False):
                gemini_key = _get_api_key("gemini")
    elif provider == "groq":
        groq_key = _get_api_key("groq")
        if Confirm.ask("\n  Also add Gemini key for embedding fallback? (recommended)", default=True):
            gemini_key = _get_api_key("gemini")
    elif provider == "gemini":
        gemini_key = _get_api_key("gemini")

    # --- Write .env ---
    env_path = Path(".env")
    _write_env(vault_path, provider, groq_key, gemini_key, env_path)
    console.print(f"\n  [green]✓[/] Config written to [cyan]{env_path.resolve()}[/]")
    console.print(f"  [dim]Make sure .env is in your .gitignore (it is by default)[/]")

    # --- Verify ---
    _verify_setup(vault_path, provider)

    # --- Done ---
    console.print(Panel(
        "[bold green]Setup complete![/]\n\n"
        "Next steps:\n"
        "  [cyan]brain ingest[/]   — index your vault (first time)\n"
        "  [cyan]brain chat[/]     — start chatting with your notes\n"
        "  [cyan]brain stats[/]    — check index status anytime",
        border_style="green",
    ))
